### PR TITLE
Fix resolve menu language field throwing internal error

### PR DESCRIPTION
**Pull request by liogate**
Hi 👋 

I've been stuck on language field too.

Here is a fix for this issue 👇 
https://github.com/rburgst/wp-graphql-wpml/issues/3

### CODE REVIEW

**Comment by liogate** [comment]
@rburgst This is removing only errors thrown by graph resolver.
I think there is still an issue on apply filters `wpml_element_language_details` receiving wrong object ?

**Comment by rburgst** [comment]
Sorry for not coming back earlier. I will test your patch and will come back next week with the results.

**Comment by rburgst** [comment]
Hi
I checked your patch and while it does remove the error, I do get errors when running the default gatsby query 

```
query NODE_LIST_QUERY($first: Int!, $after: String) {
  menus(first: $first, after: $after) {
    nodes {
      databaseId
      language
      locations
      
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

=> 
```json
{
  "errors": [
    {
      "debugMessage": "Function name must be a string",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "menus",
        "nodes",
        0,
        "language"
      ]
    },
    {
      "debugMessage": "Function name must be a string",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 5,
          "column": 7
...
```

**Comment by rburgst** [comment]
I have taken your idea and made it also work with the menu query shown above, see 71c4e10

**Pull request closed without merging**
